[project]
name = "deepsolv-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "cryptography>=45.0.6",
    "langchain-google-genai>=2.1.9",
]
